// Risk thresholds from implementation plan Section 5
export const RISK_THRESHOLDS = {
  // Blood pressure
  HIGH_BP_SYSTOLIC: 140,
  HIGH_BP_DIASTOLIC: 90,
  SEVERE_BP_SYSTOLIC: 160,
  SEVERE_BP_DIASTOLIC: 110,

  // Temperature
  FEVER_TEMP: 38.0,
  DANGER_FEVER_TEMP: 39.5,

  // MUAC
  MALNUTRITION_MUAC: 11.5,

  // TB
  TB_COUGH_WEEKS: 2,

  // Teen pregnancy
  TEEN_AGE: 19,
};

// Risk levels
export const RISK_LEVEL = {
  NONE: 'none',
  MEDIUM: 'medium',
  HIGH: 'high',
};

// Risk flag identifiers
export const RISK_FLAGS = {
  SEVERE_HYPERTENSION: 'SEVERE_HYPERTENSION',
  HIGH_BP_PREGNANCY: 'HIGH_BP_PREGNANCY',
  BLEEDING_PREGNANCY: 'BLEEDING_PREGNANCY',
  SEIZURE: 'SEIZURE',
  TEEN_PREGNANCY: 'TEEN_PREGNANCY',
  POSTPARTUM_FOLLOW_UP_MISSED: 'POSTPARTUM_FOLLOW_UP_MISSED',
  TB_COUGH_SCREENING_DUE: 'TB_COUGH_SCREENING_DUE',
  TB_FOLLOWUP_MISSED: 'TB_FOLLOWUP_MISSED',
  DANGER_FEVER: 'DANGER_FEVER',
  FEVER: 'FEVER',
  BREATHLESSNESS_CHILD: 'BREATHLESSNESS_CHILD',
  SEVERE_MALNUTRITION: 'SEVERE_MALNUTRITION',
  VACCINATION_OVERDUE: 'VACCINATION_OVERDUE',
};
